# Generated by Django 3.0.2 on 2020-07-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
                ('price', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='static/images/course/')),
            ],
        ),
    ]
