# Generated by Django 3.0.2 on 2020-07-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='static/images/blog/')),
            ],
        ),
    ]
